### ISSUE TITLE
メンバーに加わりたい！

### ISSUE THREAD

**Issue by mktoho12** [oss-gate/members#10]
サポートするの大好きです！

OSSはRubyのgemをちょっと作ったことがある程度ですが
ギークハウスとかN高等学校とかで地道に宣伝します！(ง •̀_•́)ง

**Comment by kou** [comment]
ようこそ！メンバーに追加しました！招待メールが届いていると思うので確認してみてください。

いろんな層の人に知ってもらった方が「OSS開発に参加する人を増やす」ことにつながると思うので、宣伝してくれるのはとても助かります！！！

一度、ワークショップに参加してみると宣伝しやすくなるかもしれないので、都合があうときでよいので、ワークショップにも参加してみてください！

**Comment by mktoho12** [comment]
承認ありがとうございます！
ワークショップのプロジェクトを眺めてみます！！
