### ISSUE TITLE
メンバーに加わりたいです！

### ISSUE THREAD

**Issue by ShinjiEnoki** [oss-gate/members#11]
LibreOfficeのコミュニティで活動しています。いかに貢献者を増やすかについては、LibreOfficeでも取り組みをしていましたので、興味を持ちました。

イベント運営やバグ報告のフォロー（QA分野は少し頼りないと思いますが）でお役に立てることがあればと思います。
非開発者ですので開発メンターは出来ません

よろしくお願いします。

**Comment by kou** [comment]
ようこそ！メンバーに追加しました！招待メールが届いていると思うので確認してみてください。

イベント運営で協力してもらえるのはとても助かります！今やっているワークショップは何度か開催したのでだんだんやり方がわかってきましたが、違う広がり（他のイベントとの共催とか）の模索が手付かずだったのです。

バグ報告のフォローも助かります。都合があうときでよいので今やっているワークショップにメンターとして参加してもらえるといいかなぁと思います。開発に関するフォローが必要なときもありますが、多くの場合は報告の仕方とかドキュメント通りにやってみようかと促したりとかで、開発に関係ないことなのでフォローすることはいろいろあると思います。開発に関するフォローが必要なときでも、まわりに開発に関するフォローができるメンターがいるはずなので、その人たちと連携できます。

もし、OSS Gateでなにか知見を得られたならLibreOfficeの方にも持ち帰って活用してもらえるといいなぁと思います。

できる範囲で大丈夫なので継続的によろしくお願いします！

**Comment by ShinjiEnoki** [comment]
ありがとうございます。招待メール来ていました。
まずはワークショップにメンターとして参加できればと思いました。
関西在住ですので、関東のイベントにはすぐには参加できないかもしれませんが..

**Comment by kou** [comment]
おぉ、関西ですか！

実は、東京以外でも開催したいと思っていて、今は札幌で開催できないか進めていたりします。なので、関西でも開催できるようになるとすばらしいです！

関西での開催に向けて動けそうであれば教えてください。最初の何回か（キックオフと第一回目とか）は私が関西に行って立ち上げをフォローするというのを考えています。
