### ISSUE TITLE
メンバーに加わりたいです。

### ISSUE THREAD

**Issue by ttwo32** [oss-gate/members#12]
OSSに貢献したいと思ってたのでメンバーに加わりたいです。

個人的には以下のことをやってみたいなと思ってます。
・Ruby本体の開発に加わりたい。
・Gemの修正とかIssue出してみたりとかして貢献したい。
・いずれはビギナーをサポートしたい。

よろしくお願いします。

**Comment by kou** [comment]
ようこそ！メンバーに追加しました！招待メールが届いていると思うので確認してみてください。

やりたいことがあってすばらしいです！やりたいという気持ちがあると楽しくできますからね！

少しずつでもいいので一緒にやっていきましょう！
