### ISSUE TITLE
メンバーに加わりたい！

### ISSUE THREAD

**Issue by kysnm** [oss-gate/members#13]
@kysnm と申します
イベントのスタッフをしている事が多いのですが、少しだけ OSS にも contribute した事があります
微力ながら何かお手伝い出来ればと思っております

普段は主に Rails / Ruby を使った開発をしており、片手間で JavaScript も少々嗜みます

**Comment by kou** [comment]
ようこそ！メンバーに追加しました！招待メールが届いていると思うので確認してみてください。

ぜひ一緒に活動していきましょう！OSSの開発に参加した経験があるということなので、まずはワークショップにメンターとして参加してみるのがよいと思います。未経験者のサポートもできますし、他のメンバーと話す機会にもなるので、自分はなにをするのがいいかのイメージがつきやすくなると思います。
