### ISSUE TITLE
メンバーに加わりたいです！

### ISSUE THREAD

**Issue by igara** [oss-gate/members#14]
初めまして
@igara (がらしょー)といいます。

OSS活動としてcommiterではありませんが
watch活動をおこなっています。

コミュニティを活発にしていきたいと思いますので
よろしくお願い致します。

**Comment by kou** [comment]
ようこそ！メンバーに追加しました！招待メールが届いていると思うので確認してみてください。

コミッターであるかは関係ないのでまったく問題ありません。

できる範囲のことでいいので一緒に活動してきましょう！都合があうようなら一度ワークショップにメンターとして参加してみるのがよいと思います。実際に参加してみることでいろいろ見えてくることがあって活動しやすくなると思うんです。
