### ISSUE TITLE
メンバーに加わりたい！

### ISSUE THREAD

**Issue by unsolublesugar** [oss-gate/members#15]
はじめまして。
スタートアップでCocos2d-xやUnityを使ってゲームアプリ開発をしております、@unsolublesugar と申します。

Twitter経由でOSS Gateの存在を知りまして、取り組み内容に興味を持ちました。
ぜひともメンバーとして参加させていただきたいです。

OSS活動としては、Firefox OSコミュニティ、 Mozilliansで少し関わらせていただいた程度です。
勉強会での登壇やハンズオンでのチューターなども数回経験があります。
http://unsolublesugar.com/category/gadget/firefox-os/

最近は積極的な参加ができておらず、何かしらの形でOSS活動を行なっている方の支援ができればと思っておりました。ブログでの情報発信等、少しでも協力ができれば幸いです。

GitHubは会社で導入し始めたところなので、運用方法なども学ばせていただければと思っております。
よろしくお願いいたします。

**Comment by kou** [comment]
ようこそ！メンバーに追加しました！招待メールが届いていると思うので確認してみてください。

チューターの経験があるのはとても頼もしいです！情報発信ができることも頼もしいです。できる範囲でいいので一緒に継続的に活動していきましょう！

OSS Gateの活動から自分にとっても得られることがあるというのはとてもよいことだと思うので、運用方法などで得られることがあるならたくさん活用してください！

**Comment by unsolublesugar** [comment]
ありがとうございます！今後ともよろしくお願いいたします:blush:
