### ISSUE TITLE
メンバーに加わりたい！

### ISSUE THREAD

**Issue by hideshis** [oss-gate/members#16]
はじめまして， hideshis と申します。
私は，ソフトウェア開発に関する研究を行っており，その一環でOSSの開発データを利用したりしています．
いまはまだOSS開発に携わってはいないのですが，近いうちにやってみたいとは思っています．
また，日本国内でもっとOSS開発が活発になれば良いのにな，とも思っています．
微力ながらお力添えさせていただきたいと思います．

**Comment by kou** [comment]
ようこそ！メンバーに追加しました！招待メールが届いていると思うので確認してみてください。

ぜひOSS開発に参加していきましょう！機会があればワークショップに参加してみてください！
