### ISSUE TITLE
Want to join the group

### ISSUE THREAD

**Issue by hiroppy** [oss-gate/members#17]
@abouthiroppy といいます。

oss活動をしたいという方のサポートをしたいと思っており、
oss-gateの活動に興味があるのでよろしくお願いします:)

OSS Gateワークショップ(2016-11-26)にメンターとして参加させていただく予定です。
よろしくお願いします！

**Comment by kou** [comment]
ようこそ！
oss-gate/membersに招待したので通知がいっていると思います。確認してみてください。

11月のワークショップへの参加もさすがです！
一緒にOSS開発に参加する人を増やしていきましょう！
