### ISSUE TITLE
メンバーに加わりたい！

### ISSUE THREAD

**Issue by kun432** [oss-gate/members#20]
京都での協力依頼がタイムラインに流れてたのを見て来ました。

サーバ系なので、ちょびっとPRとfolkしたぐらいの経験しかないですが、関西で参加させてもらえればと思ってます。よろしくお願いします。

**Comment by kou** [comment]
ようこそ！招待がいっているはずなので確認してください！

京都での活動は始まったばかりなのでとても頼もしいです！
京都・大阪あたりでの活動は https://gitter.im/oss-gate/kansai でも相談しているので、そちらにもぜひ参加してください！

**Comment by kun432** [comment]
参加できました。よろしくお願いします

**Comment by masayuki14** [comment]
よろしくおねがいします！
