### ISSUE TITLE
メンバーに加わりたい！ 

### ISSUE THREAD

**Issue by endianoia** [oss-gate/members#21]
はじめまして。開発経験はあまり無いのですが「OSS開発に参加する人を増やす取り組み」に共感しｍして、参画したく思います。
都内にて活動しております。

**Comment by kou** [comment]
ようこそ！
@oss-gate/members への招待メールが届いていると思うので確認してみてください！

都内であれば、9月2日開催の[OSS Gate東京ワークショップ for 高専 2017-09-02](https://oss-gate.doorkeeper.jp/events/63111)あるいは[OSS Gate東京ふりかえり2017-09](https://oss-gate.doorkeeper.jp/events/63831)に参加して既存メンバーと話をしてみるのがよさそうに思います！（まだイベントページはできていませんが、9月30日にもワークショップが開催する予定なので、それでもよいです。）

開発経験はあまりないとのことですが、もしかしたら、8月28日開催の[OSS Gate東京ミートアップ2017-08-28](https://oss-gate.doorkeeper.jp/events/63053)もアリかもしれません。


https://gitter.im/oss-gate/general に既存メンバーがオンラインでやりとりしている場所があるので、そこらへんで雰囲気を見ておくのもよいと思います！

一緒にOSS開発に参加する人を増やしていきましょう！
