### ISSUE TITLE
メンバーに加わりたい！

### ISSUE THREAD

**Issue by 723gt** [oss-gate/members#23]
先日のOSS島根のLTで興味を持ちOSS開発の最初の一歩として参加したいと思いました。
主な活動範囲は関西です。

**Comment by kou** [comment]
OSSの開発に参加していきましょう！
@sakasita001 やりましたね！

oss-gate/membersチームへの招待がいっているので確認してください。

関西なら https://gitter.im/oss-gate/kansai にも参加すると情報を入手しやすいのでどうぞ！
11月18日に大阪でワークショップがある https://oss-gate.doorkeeper.jp/events/65122 ので、それに参加するのがよさそうです！

**Comment by 723gt** [comment]
ありがとうございます。
11/18のワークショップも参加させていただきます
よろしくお願いします！

**Comment by sakasita001** [comment]
反応が遅くなりました…
メールは届いてたので鼻歌歌って仕事してました。

@723gtさん、よろしくお願いします！
