### ISSUE TITLE
メンバーに加わりたい！

### ISSUE THREAD

**Issue by ishikawa999** [oss-gate/members#24]
OSS島根で紹介していただき興味を持ちました。
私もついこの前に門をくぐったばかりで、OSC島根では[「怖くない？オープンソースへの貢献」](https://www.slideshare.net/ishikawa_mizuki/ss-80878999) というタイトルで初心者の気持ちについて話したりしました。
やはり個人では門をくぐるにも、継続するにも不安感が大きいので、それを払拭する素晴らしい取り組みだと思います！
島根で活動しているのでなかなか積極的に参加するということはできないかもしれませんが、何かしらの形でOSS未経験の方の後押しをできればと思います。

**Comment by kou** [comment]
ようこそ！
"Members"というチームへのinvitaionが届いていると思うので確認してみてください！


> 島根で活動しているのでなかなか積極的に参加するということはできないかもしれませんが、何かしらの形でOSS未経験の方の後押しをできればと思います。

島根でもOSS Gateを始めませんか！？
https://gitter.im/oss-gate/shimane で相談するのはどうでしょうか。

島根にはファーエンドテクノロジーさん以外にもOSSの開発に参加している企業があるので、始めやすそうな気がします。また、広島でも立ち上がろうとしているので、広島の人たちや関西の人たちとも一緒に相談しながらできるとよさそう！

東京では oss-gate/workshop#408 のようにピクシブさんがMastodonに特化したワークショップを開催しました。ファーエンドテクノロジーさん主体でRedmineに特化したワークショップ開催から始めるのはやり始めやすいかも！（Redmine大阪のときに、前田さんにはRedmineの開発に参加する人を増やすためにRedmineに特化したOSS Gateワークショップを開催するのはどうですか！？とざっくり話したことはあります。）

**Comment by sakasita001** [comment]
お世話になっております。

OSS GATE　島根につきまして、ぜひやらせてください。

先日のOSC島根にて前田社長とも話をさせていただきました。
広島が終わってから島根のご相談をと思っておりました。

**Comment by ishikawa999** [comment]
"Members"チームへのinvitaion、確認しました。ありがとうございます。

OSS Gate 島根、素晴らしいです！

**Comment by kou** [comment]
チームに入ったので、ここはクローズしますね。

OSS Gate島根、やりましょう！

@ishikawa999 どうやって進めていくか（やり方とか時期とか）みたいなことは https://gitter.im/oss-gate/shimane で相談できるといいんじゃないかと思うんですが、Gitterへのログイン方法ってわかりますか！？（GitHubアカウントでログインできます。）

**Comment by ishikawa999** [comment]
@kou 
ログインしました。ありがとうございます！
