### ISSUE TITLE
メンバーに加わりたい！ 

### ISSUE THREAD

**Issue by swamp09** [oss-gate/members#25]
二人目の東京ミートアップの会場係です。

OSS開発は未経験でしたが、ミートアップに参加するようになって徐々に活動できるようになりました。
OSS gate が継続して開催できるようお手伝いしたいと思っています。

よろしくお願いします！

**Comment by kou** [comment]
「Members」チームにinviteしました！

ミートアップの効果があってすごくよかったです！OSS Gateをはじめてよかったです！

継続することは私達がとても大事にしていることです！
継続してOSSの開発に参加する人を増やしていきましょう！
