### ISSUE TITLE
メンバーに加わりたいです!

### ISSUE THREAD

**Issue by get-me-power** [oss-gate/members#30]
はじめまして、IKといいます。
`OSSGate`の活動に大変興味を持ちました！
まだ学生ですが、微力ながら何かお手伝い出来ればと思っております。

**Comment by kou** [comment]
さすがです！
invitationが届いていると思うので確認お願いします！

GitHub上での権限はこれで得られますが、相談事などは https://gitter.im/oss-gate/general と各地域ごとのチャット（たとえば東京なら https://gitter.im/oss-gate/tokyo ）でやっているのでGitterにも参加してもらえるとどんな形でお手伝いするのがよさそうか見つかりやすいはずです！

**Comment by get-me-power** [comment]
@kou 

承知しました！ありがとうございます！
