### ISSUE TITLE
私はメンバーになりたいです！

### ISSUE THREAD

**Issue by june29** [oss-gate/members#7]
ただの OSS 開発経験者の @june29 と申します。

ふだんから、若手ソフトウェア開発者(現役学生含む)との接点がちょこちょこあって、
彼ら彼女らが「踏み出してみたい」と願ったときに後押ししたい気持ちがあります。

また、宣伝や会場提供などでもお手伝いできることがあるかもしれません。
どうぞよろしくお願いいたします！

**Comment by sezemiadmin** [comment]
ありがとうございます! 招待しましたー

**Comment by kou** [comment]
ようこそ！
