### ISSUE TITLE
メンバーに加わりたい！

### ISSUE THREAD

**Issue by kurotaky** [oss-gate/members#9]
@kurotaky と申します。
最近は[第4回Rails Girls Tokyo](http://railsgirls.com/tokyo-2014-09-21)やRails Girls, More!でコーチをしていました。仕事・趣味でOSSを活用していまして、OSS活動に関わる人を増やしたいという思いがあります。

この活動のお手伝いをしたいです。よろしくお願いします！ :smiley:

**Comment by kou** [comment]
ようこそ！追加しました！

メンバーは https://gitter.im/oss-gate/general でいろいろ相談しているのでこちらもご活用ください！

**Comment by kurotaky** [comment]
追加ありがとうございます！承知しました〜
